apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-server-cert
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: addon-operator
  name: addon-operator-metrics
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: addon-operator
status:
  loadBalancer: {}
