apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: webhook-service
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: addon-operator-webhook-server
status:
  loadBalancer: {}
