apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- addons.managed.openshift.io_addoninstances.yaml
- addons.managed.openshift.io_addonoperators.yaml
- addons.managed.openshift.io_addons.yaml
- deployment.yaml
- metrics.service.yaml
- rbac.yaml
- monitoring/servicemonitor.yaml
- webhook

